### ISSUE TITLE
ios11下那个问题解决了吗？

### ISSUE THREAD

**Issue by bingolib** [Ossey/XYRearrangeCell#1]
您好~ #warning Mark: iOS11 下 locationInView:bug 获取当前手指所在的点存在错误，导致瞬间移动乱窜，待解决。
例如设置个开关按钮，打开后点击后cell可以拖动，关闭后cell禁止拖动。该怎么做？谢谢~

**Comment by tuxi** [comment]
- 现在没发现坐标问题了，
- 开关需求:
由于`UIScrollView+RollView `中是通过一个长按手势控制cell拖动的，而`UILongPressGestureRecognizer `有一个属性`enabled`可以控制手势是否有效，那么我们可以在`UIScrollView+RollView`中添加一个属性控制手势的`enabled `属性即可，我在`UIScrollView+RollView`中也添加了这个属性及相关demo，并commit。
O(∩_∩)O谢谢你的建议。

**Comment by bingolib** [comment]
非常感谢~已解决
