### ISSUE TITLE
您好~拖动cell时 怎么获取cell移动前index和移动结束后index。

### ISSUE THREAD

**Issue by bingolib** [Ossey/XYRearrangeCell#2]
拖动cell时  怎么获取cell移动前index和移动结束后index。
看代码BCLOG(@"lastRollIndexPath:%ld-------newIndexPath:%ld", self.lastRollIndexPath, newIndexPath);有此打印。 
发现block回调结束后 仍有此打印。因此根据index获取数据有异。请教原因。
非常非常感谢~~

**Comment by tuxi** [comment]
不好意思，我的邮箱刚收到这个问题，不知道你解决了没有；

下面是我的解决方法:
重新定义了XYRollingBlock，给它添加了手指的开始移动前的indexPath和当前所在的indexPath两个参数
` typedef void(^XYRollingBlock)(NSIndexPath *originalIndexPath, NSIndexPath *currentIndexPath);`

你可以使用下面方法获取cell移动前index和移动结束后index的改变:
```
    [self.tableView xy_rollViewFormOriginalDataSourceBlock:^NSArray * _Nonnull{
        return self.plans;
    } rollingBlock:^(NSIndexPath * _Nonnull originalIndexPath, NSIndexPath * _Nonnull currentIndexPath) {
        NSLog(@"%@-------%@",originalIndexPath, currentIndexPath);
    } newDataSourceBlock:^(NSArray * _Nullable newData) {
      
    }];
```
